### PR TITLE
created Graph_Theory and added DFS.cpp

### PR DESCRIPTION
**Pull request by DravitLochan**
added DFS in Graph_Theory. Will be adding BFS soon.

### CODE REVIEW

**Comment by domfarolino** [comment]
Don't sweat failed tests. Not a huge deal though if you really want to fix the commit messages you technically could lol. I'll get around to checking out the code tomorrow afternoon and recommend any changes if necessary. Thanks a lot for the contribution @DravitLochan

**Comment by DravitLochan** [comment]
thanks. Will be waiting for the fix and then merge. ;)

**Comment by domfarolino** [comment]
Hey, we added Quicksort just a bit ago if you want to revert that commit from your PR that would be nice sorry. Also, regarding the code in your DFS, could you maybe put it in a DFS folder. Also could you check out the Google C++ Style Guide's formatting section? It can be found in the CONTRIBUTING.MD file in the root. I just use it to keep the formatting in this repo totally uniform. Thanks a lot

**Comment by DravitLochan** [comment]
being a noob, I again lack this ability to create test files. Please help.

**Comment by domfarolino** [comment]
Can you check out the Google C++ Style Guide's formatting section? There's a link to it in the CONTRIBUTING.md file

**Comment by DravitLochan** [comment]
I know that this is annoying, but I still don't get that. I find that someone else too has put up a PR for DFS. Previously too I had to revert my commit for quick sort. Please help me.!!

**Comment by DravitLochan** [comment]
Listening?

**Comment by domfarolino** [comment]
Yep are you? Read my last comment and make the appropriate changes. Also, why is there like ~50 commits in this PR?

**Comment by DravitLochan** [comment]
Ok. Help me with this. Close this pr.
I'll open A new one. I think I messed with this one!
Thanks

**Pull request closed without merging**
