### PR TITLE
algo(countingSort): a linear time sorting algo

### PR DESCRIPTION
**Pull request by saksham15082**
The description of count function is given in the code comments.

### CODE REVIEW

**Comment by saksham15082** [comment]
@domfarolino  finally. I was able to match the required style.Please merge if it is adequate else suggest changes.Though thanks for coopereting and guiding me step by step.

**Comment by saksham15082** [comment]
@domfarolino  also please close my other pull requests as they contain error.

**Comment by domfarolino** [comment]
If you could change the folder and file names from countSort => countingSort that would be great. I'll be making a few style changes later on and then I should be able to merge

**Comment by saksham15082** [comment]
@domfarolino  so should i send a new pull request?

**Comment by domfarolino** [comment]
@saksham15082 No you can just update this PR instead of making a new one. Push code to the same branch with a nicely formatted commit message and it will auto-update the PR

**Pull request closed without merging**
