### PR TITLE
algo(dominator): added algorithm to resolve 11902 - Dominator UVA problem

### PR DESCRIPTION
**Pull request by I-am-Gabi**
Description problem: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=229&page=show_problem&problem=3053

I can add more comments to the code, if it's necessary. Sorry for any mistake in my English.

### CODE REVIEW

**Comment by domfarolino** [comment]
@I-am-Gabi Don't sweat the failed tests. If you really want to modify your commit messages you can [do so](https://help.github.com/articles/changing-a-commit-message/) else its not a huge deal. I'll check out the PR tomorrow afternoon thanks a lot!

**Comment by domfarolino** [comment]
@I-am-Gabi Ok if we reopen? I need to modify the gitmagic-bot settings that I'm testing out haha!

**Comment by I-am-Gabi** [comment]
I changed something that I forgot, like the test.in and test.out... now it's ok, I can try again :)

**Comment by I-am-Gabi** [comment]
OK! Now I passed :)

**Comment by domfarolino** [comment]
Thanks a lot for the contribution @I-am-Gabi . Feel free to add any more algorithms (especially UVa problems). Also if you wanted to add more solution documentation, feel free to keep updating your fork.

**Comment by I-am-Gabi** [comment]
Thanks @domfarolino :)

**Pull request merged**
