### PR TITLE
Usaco problems PR 2

### PR DESCRIPTION
**Pull request by maiquynhtruong**
Hi there I made commit messages following the contributing guide this time and I also added input and output files for the problems.

### CODE REVIEW

**Comment by maiquynhtruong** [comment]
Ooops not quite perfect :/

**Comment by domfarolino** [comment]
Will be getting to right after finals ;)

**Comment by maiquynhtruong** [comment]
That works. Good luck on your finals!

**Comment by maiquynhtruong** [comment]
Did you actually work on all the problems before merging?

**Comment by domfarolino** [comment]
2 reasons I did not. 1, it seems you deleted your fork of the repo so I didn't have a branch to push any changes to if I wanted to modify the PR. 2, everything looked solid enough and I didn't really have any big concerns. I might touch up some style conventions at some point because I'm crazy, but it was looking pretty good honestly. Thanks!

**Comment by maiquynhtruong** [comment]
Oops I thought you forgot about this PR so I deleted the fork. I can create a fork and make another PR if you want to make style changes.
Let me know if you want to do so.

**Comment by domfarolino** [comment]
Shouldn't be an issue now that they're merged. Thanks though!

**Pull request merged**
