### PR TITLE
algo(countingSort): a linear time sorting algo

### PR DESCRIPTION
**Pull request by saksham15082**
The description of count function is given in the code comments.

### CODE REVIEW

**Comment by saksham15082** [comment]
@domfarolino  sorry i already made a new pr.

**Comment by saksham15082** [comment]
@domfarolino  from next time onwards ill modify the old one.

**Comment by saksham15082** [comment]
@domfarolino please merge my previous.

**Comment by domfarolino** [comment]
Check out the Google C++ Style Guide linked in the contributing markdown file. I referenced it in one of your previous pull requests.

**Comment by domfarolino** [comment]
^

**Comment by domfarolino** [comment]
Closing due to inactivity. Please comment if you'd still like to make changes

**Pull request closed without merging**
