### PR TITLE
countingsort

### PR DESCRIPTION
**Pull request by rahul26081995**
#2

### CODE REVIEW

**Comment by domfarolino** [comment]
Checkout the Contributing.MD file in root

**Comment by rahul26081995** [comment]
Permission is denied when trying to push via new branch. That's why I forked it.

**Comment by domfarolino** [comment]
Sorry, mainly I meant check out the Google C++ style guide for the code style

**Comment by domfarolino** [comment]
Sorry, but going to close this due to inactivity (style concerns haven't been addressed :( ), but if you'd still like to make changes let me know.

**Pull request closed without merging**
