### PR TITLE
Algo/cpp quicksort

### PR DESCRIPTION
**Pull request by denvaar**
Quicksort algorithm

### CODE REVIEW

**Comment by domfarolino** [comment]
@denvaar Could you put the space complexity in the comments up near the time complexity?

**Comment by denvaar** [comment]
@domfarolino sure thing -- I'll do it later tonight

**Comment by denvaar** [comment]
@domfarolino got it

**Comment by domfarolino** [comment]
@denvaar Cool thanks. I think the linked list and atoi() implementation commits are in this PR as well, maybe the commits were included in the same branch. Mind if I get rid of the `Data_Structrues` and `Algorithms_From_Scratch` folders in this branch so we can merge one at a time?

**Comment by denvaar** [comment]
@domfarolino sure, you can change whatever you like.

**Pull request merged**
